// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf1MYhYhKZg0Ss9d2E0ebH25XP5Bte7Y0',
    appId: '1:165262957316:web:aaf2eae9ec14e974134e51',
    messagingSenderId: '165262957316',
    projectId: 'tashlih-app-b5b20',
    authDomain: 'tashlih-app-b5b20.firebaseapp.com',
    storageBucket: 'tashlih-app-b5b20.firebasestorage.app',
    measurementId: 'G-EN0J97E1TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADmAeZH3NF9i6jP_kjvg5mL3JV5Cdj5CY',
    appId: '1:165262957316:android:0f07d4ef7c3d060d134e51',
    messagingSenderId: '165262957316',
    projectId: 'tashlih-app-b5b20',
    storageBucket: 'tashlih-app-b5b20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLnrHikpg9dCYLZ6gwA6BbaJfVzlus3qg',
    appId: '1:165262957316:ios:5f57b41ed70a4310134e51',
    messagingSenderId: '165262957316',
    projectId: 'tashlih-app-b5b20',
    storageBucket: 'tashlih-app-b5b20.firebasestorage.app',
    iosBundleId: 'com.example.tashlihApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLnrHikpg9dCYLZ6gwA6BbaJfVzlus3qg',
    appId: '1:165262957316:ios:5f57b41ed70a4310134e51',
    messagingSenderId: '165262957316',
    projectId: 'tashlih-app-b5b20',
    storageBucket: 'tashlih-app-b5b20.firebasestorage.app',
    iosBundleId: 'com.example.tashlihApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf1MYhYhKZg0Ss9d2E0ebH25XP5Bte7Y0',
    appId: '1:165262957316:web:e3608005fd0ba07b134e51',
    messagingSenderId: '165262957316',
    projectId: 'tashlih-app-b5b20',
    authDomain: 'tashlih-app-b5b20.firebaseapp.com',
    storageBucket: 'tashlih-app-b5b20.firebasestorage.app',
    measurementId: 'G-LQV6XEDDPQ',
  );
}
